baseURL: "https://connortech.me"
title: Connor's Space
paginate: 8
theme: hugo-PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true

googleAnalytics: UA-64319594-2

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Photography Site
          url: http://www.connorphoto.com
          weight: 1 
        - name: Blog Archives
          url: /archives/
          weight: 5
        - name: Tags
          url: /tags/
          weight: 10

params:
  env: production
  description: "Simple website for Connor's thoughts"
  author: Connor
  # author: ["Me", "You"] # multiple authors
  ShowReadingTime: true
  defaultTheme: auto
  ShowShareButtons: true
  displayFullLangName: true
  # images: ""
  # assets:
  #   favicon: '<path / external url>'

  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "#"
    imageTitle: my image
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Hello! \U0001F44B"
    Content: >
      Welcome to my space! Just a simple website to share my random thoughts and projects I am working on.

  socialIcons:
    - name: twitter
      url: "https://twitter.com/ConnorTech"
    - name: adobestock
      url: "https://stock.adobe.com/contributor/204687735/Connor"
    - name: instagram
      url: "https://www.instagram.com/connorkoehler/"
    - name: youtube
      url: "https://www.youtube.com/channel/UCuc0tRKTs867Crd2QH4gCag"
    - name: linkedin
      url: "https://www.linkedin.com/in/conradkoehler/"
    - name: github
      url: "https://github.com/ConnorKoehler"
    - name: buymeacoffee
      url: "https://buymeacoffee.com/ConnorTech"

taxonomies:
  category: categories
  tag: tags
  series: series

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
